version: "3.8"

services:
  server:
    container_name: graphql_server_container
    image: graphql_server_image
    build:
      dockerfile: "Dockerfile.prod"
      target: production
    command: npm start
    ports:
      - 4000:4000
    depends_on:
      database:
        condition: service_healthy
  
