version: "3.8"

services:
  server:
    container_name: city_guid_server_prod
    image: graphql_server_image
    build:
      dockerfile: "Dockerfile"
      target: production
    environment:
      - NODE_ENV=production
    command: npm start
    ports:
      - 4000:4000
    depends_on:
      database:
        condition: service_healthy
  
