version: "3.8"

services:
  back:
    build:
      dockerfile: "Dockerfile"
    volumes:
      - ./:/app:rw,cached
      - /app/nodes_module
    ports: 5002:5002
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: wilderDB
      POSTGRES_PASSWORD: example
      POSTGRES_DB: city_guid
      PGDATA: /var/lib/postgresql/data/customDataFolder
    volumes:
      - ./dbData:/var/lib/postgresql/data/customDataFolder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d city_guid -U postgresl"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
