version: "3.8"

services:
  server:
    container_name: city_guid_server_test
    image: graphql_server_image
    build:
      dockerfile: "Dockerfile"
      target: development
    volumes:
      - ./:/app:rw,cached
    environment:
      - NODE_ENV=test
    command: npm run dev
    ports:
      - $SERVER_LOCAL_PORT_DEV:$SERVER_DOCKER_PORT_DEV
    depends_on:
      database_test:
        condition: service_healthy

  database_test:
    container_name: city_guid_pg_test
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $DB_USER_TEST
      POSTGRES_PASSWORD: $DB_PASSWORD_TEST
      POSTGRES_DB: $DB_NAME_TEST
      PGDATA: /var/lib/postgresql/data/customDataFolder
    ports:
      - $DB_PORT:$DB_DOCKER_PORT
    volumes:
      - ./db_test:/var/lib/postgresql/data/customDataFolder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d city_guid_test -U wilder_test"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  adminer:
    container_name: city_guid_adminer_test
    image: adminer
    restart: always
    ports:
      - $ADMINER_PORT:$ADMINER_DOCKER_PORT
    depends_on:
      database_test:
        condition: service_healthy

  pgadmin:
    container_name: city_guid_pgadmin4_test
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL_TEST
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD_TEST
    ports:
      - $LOCAL_PORT_LISTENNIG_PGADMIN:$DOCKER_HTTP_PORT
    depends_on:
      database_test:
        condition: service_healthy
