version: "3.8"

services:
  server:
    build:
      dockerfile: "Dockerfile"
    volumes:
      - ./:/app:rw,cached
    ports:
      - 4000:4000
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: wilderDB
      POSTGRES_PASSWORD: password
      POSTGRES_DB: city_guid
      PGDATA: /var/lib/postgresql/data/customDataFolder
    volumes:
      - ./dbData:/var/lib/postgresql/data/customDataFolder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d city_guid -U wilderDB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      database:
        condition: service_healthy
