version: "3.8"

services:
  server:
    container_name: graphql_server_container
    image: graphql_server_image
    build:
      dockerfile: "Dockerfile.dev"
      target: development
    volumes:
      - ./:/app:rw,cached
    command: npm run dev
    ports:
      - 4000:4000
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: postgresql_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: wilderDB
      POSTGRES_PASSWORD: password
      POSTGRES_DB: city_guid
      PGDATA: /var/lib/postgresql/data/customDataFolder
    ports:
      - "5432:5432"
    volumes:
      - ./dbData:/var/lib/postgresql/data/customDataFolder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d city_guid -U wilderDB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  adminer:
    container_name: adminer_container
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: wilder@wilder.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "4050:80"
    depends_on:
      database:
        condition: service_healthy
